__title__ = 'pysigep'
__description__ = 'API python para uso dos serviços fornecidos pelo ' \
                  'SIGEPWeb dos Correios '
__version__ = '0.1.0'
__url__ = 'https://github.com/mstuttgart/pysigep'
__download_url__ = 'https://github.com/mstuttgart/pysigep'
__author__ = 'Michell Stuttgart'
__author_email__ = 'michellstut@gmail.com'
__maintainer__ = 'Michell Stuttgart'
__maintainer_email__ = 'michellstut@gmail.com'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2016-2018 Michell Stuttgart'
__status__ = 'Development'
